### ISSUE TITLE
Gitter chat room for HashGraph users

### ISSUE THREAD

**Issue by 0zAND1z** [lbaird/swirlds-demos#5]
@lbaird , Maybe start a Gitter.im chat room to address some of the educational curves for users rather than being filed as an issue?

**Comment by alexgodwin1** [comment]
Hi @kggp1995, we do currently have a Hashgraph Develop group where we look to answer all technical questions. We are also actively looking at Gitter as a solution and we may migrate in the future if that is the preferred platform. 

Hashgraph Telegram Groups 

Community group - https://t.me/hashgraph
Developer group - https://t.me/hashgraphdev
Hashgraph Announcements - https://t.me/hashgraphnews

**Comment by vkobel** [comment]
What about Slack? Telegram is not really suited for discussing dev IMO.

**Comment by kakins** [comment]
Just a comment, I believe there is a gitter room already, last time I checked I was pretty much the only one there :)

I agree though, I prefer Gitter as a more developer central chat.  For some reason I'm not a huge fan of telegram.

**Comment by kylearmour** [comment]
There is a gitter, but its not really used. We have a specific channel for DEV on telegram at http://t.me/hashgraphdev - and a forum is being built at http://hashgraphboard.com

**Comment by 0zAND1z** [comment]
Seems like the developer community is happy with Discord. Closing this thread for now.

Wow, good times of 2017 :)
